hmcts/bar-web

- Jenkinsfile
Can someone please merge this so that code can be deployed into "test" environment (for QA Testers to test).
> Test deploy uncommented.

- .angular-cli.json
- package.json
- sonar-project.properties
- src/app/core/components/payment-instruction-list/payment-instruction-list.component.spec.ts
- src/app/core/models/feesearch.model.spec.ts
- src/app/core/models/feesearch.model.ts
- src/app/core/models/payment-parent.model.spec.ts
- src/app/core/models/payment-parent.model.ts
- src/app/core/models/user.model.spec.ts
- src/app/core/pipes/upper-case-first.pipe.spec.ts
- src/app/core/services/feelog/feelog.service.spec.ts
- src/app/core/services/payment-instructions/payment-instructions.service.spec.ts
- src/app/core/services/payment-instructions/payment-instructions.service.ts
- src/app/routes/services/authguard.service.spec.ts
- src/app/shared/models/util/model.utils.spec.ts
- src/app/shared/pipes/format-pound.pipe.spec.ts
- src/app/shared/services/auth/auth.service.spec.ts
- src/app/shared/services/interceptors/currency.converter.interceptor.spec.ts
- src/app/test-utils/test-utils.ts
restore sonar report and increase coverage
> [AK] incerasing coverage

- express/infrastructure/security.js
The url for getting users selected site has changed on the server (the url mapping wasn't correct) so the changes needed to be introduced here at bar-web also
```
[ ] Yes
[X] No
```
The functional tests are failing on Jenkins, however it run successful locally against the PR. Here is the test result:
```
+ export E2E_FRONTEND_URL=https://bar-web-pr-398.service.core-compute-preview.internal
+ E2E_FRONTEND_URL=https://bar-web-pr-398.service.core-compute-preview.internal
+ export E2E_PROXY_SERVER=proxyout.reform.hmcts.net:8080
+ E2E_PROXY_SERVER=proxyout.reform.hmcts.net:8080
+ export 'E2E_PROXY_BYPASS=*beta*LB.reform.hmcts.net'
+ E2E_PROXY_BYPASS='*beta*LB.reform.hmcts.net'
+ export E2E_FRONTEND_NODE_ENV=production
+ …
```
> fix url mapping on app side and using the new url here

- acceptance-tests/test/end-to-end/pages/steps.js
- acceptance-tests/test/end-to-end/pages/steps_file.js
- acceptance-tests/test/end-to-end/tests/BARPostClerk_test.js
- src/app/core/components/payment-instruction/payment-instruction.component.html
- src/app/core/components/payment-instruction/payment-instruction.component.ts
- src/app/shared/components/navigation/navigation.component.html
> BAR-606,608,609 Implemented

- src/app/app.module.ts
- src/app/core/components/payment-review-summary/payment-review-summary.component.ts
- src/app/core/test-mocks/paymentstate.service.mock.ts
- src/app/shared/components/action-filter/action-filter.component.ts
- src/app/shared/components/stats/stats.component.html
- src/app/shared/components/stats/stats.component.ts
- src/app/shared/services/action/paymentaction.service.spec.ts
- src/app/shared/services/action/paymentaction.service.ts
- src/app/shared/services/cache/cache.service.ts
- src/app/shared/services/feature/feature.service.spec.ts
- src/app/shared/services/feature/feature.service.ts
- src/app/shared/services/state/paymentstate.service.spec.ts
- src/app/shared/services/state/paymentstate.service.ts
> [BAR-690][AK] Introduce caching in angular for the reference data

- src/app/core/components/feelogedit/feelogedit.component.spec.ts
- src/app/core/components/feelogedit/feelogedit.component.ts
- src/app/core/components/feelogedit/main/feelog.main.component.html
- src/app/core/components/feelogedit/main/feelog.main.component.spec.ts
- src/app/core/components/feelogedit/main/feelog.main.component.ts
https://tools.hmcts.net/jira/browse/BAR-713
Fix the issue with displaying the error message. It was related to appinsight wrapped exception
```
[ ] Yes
[X] No
```
**PR link:**
https://bar-web-pr-408.service.core-compute-preview.internal
> [BAR-713] fix error display issue on edit component

- src/app/core/components/check-submit/check-submit.component.html
- src/app/core/components/check-submit/check-submit.component.spec.ts
- src/app/core/components/check-submit/check-submit.component.ts
- src/app/core/components/login-form/login-form.component.html
- src/app/core/components/login-form/login-form.component.ts
- src/app/core/components/payment-review-summary/payment-review-summary.component.html
- src/app/core/components/payment-review-summary/payment-review-summary.component.spec.ts
- src/app/core/components/payment-review-summary/payment-review-summary.component.ts
- src/app/core/services/paymentoverview/paymentsoverview.service.ts
- src/app/shared/components/action-filter/action-filter.component.html
- src/app/shared/components/action-filter/action-filter.component.spec.ts
- src/app/shared/components/action-filter/action-filter.component.ts
- [&#10004;] commit messages are meaningful and follow good commit message guidelines
- [&#10004;] README and other documentation has been updated / added (if needed)
- [&#10004;] tests have been updated / new tests has been added (if needed)
https://tools.hmcts.net/jira/browse/BAR-588
A component was created which handles the action menu item for all different roles and pages.
To make the changes fully functional the back-end (https://github.com/hmcts/bar-apps/pull/208) changes should be merged and deployed first.
```
[ ] Yes
[x] No, but if this PR goes before the back-end …
```
> [BAR-588][AK] add counter on fee clerk check and submit page

- express/app.js
-
There was a number validation in node for user_id which does not work anymore with sIdam as the user id there is UUID
```
[ ] Yes
[X] No
```
> remove user id validation

- infrastructure/aat.tfvars
> update idam url to the strategic one on aat

- acceptance-tests/test/end-to-end/pages/steps_file.js
- acceptance-tests/test/end-to-end/tests/BARFeeClerk_test.js
> BAR-707 implemented

- charts/bar-web/requirements.yaml
- infrastructure/demo.tfvars
> Bar web demo repoint

- src/app/core/components/feelogedit/detail/feedetail.component.ts
https://tools.hmcts.net/jira/browse/BAR-565
Check if the newly opened fee contains a remission and open or close the fee section respectively 
```
[ ] Yes
[X] No
```
> [BAR-565] Close remission section if not needed

- karma.conf.js
- src/app/core/components/feelogedit/detail/feedatail.validator.ts
- src/app/core/components/feelogedit/detail/feedetail.component.html
- src/app/core/components/feelogedit/detail/feedetail.component.spec.ts
- src/app/core/components/feelogedit/detail/feedetail.component.ts
> BAR-566,567,569 implemented

- express/mvc/controllers/FeeController.js
- src/app/core/components/feelogedit/detail/feedatail.validator.ts
- src/app/core/components/feelogedit/detail/feedetail.component.spec.ts
https://tools.hmcts.net/jira/browse/BAR-562
Adding angular validation to case reference, and also making some changes on nodejs side not to swallow the exception although we are not handling them on angular. (But at least it's visible on console)
```
[ ] Yes
[X] No
```
> [BAR-562][AK] Case reference proper validation

- express/infrastructure/errors.js
- express/infrastructure/security.js
- express/mvc/controllers/PaymentsOverviewController.js
- express/test/infratructure/errors.test.js
- express/test/mvc/controllers/PaymentsOverviewController.test.js
- server.js
https://tools.hmcts.net/jira/browse/BAR-614
Removing useless logging, removing emails from logs, trying to make a general approach to log and fwd the errors.
```
[ ] Yes
[X] No
```
> [BAR-614] Optimise nodejs logging

- charts/bar-web/requirements.yaml
Increase chart version for bar-api to 0.0.3
```
[ ] Yes
[X] No
```
> increase chart level to 0.0.3

- src/app/core/components/feelogedit/detail/feedetail.component.ts
> [BAR-766][AK] fix back button on fee edit page

- src/app/shared/components/details/details.component.scss
> [BAR-769][AK] fix date and table formatting on senior fee clerks page

- src/app/core/components/feelogedit/detail/feedetail.component.html
- src/app/core/components/feelogedit/feelogedit.component.scss
- src/app/core/components/feelogedit/main/feelog.main.component.html
- src/app/core/components/feelogedit/main/feelog.main.component.spec.ts
> BAR-543 - Update validate payment screen after adding partial remission

- express/app.js
- express/infrastructure/security.js
- express/mvc/controllers/SitesController.js
- express/mvc/controllers/index.js
- express/services/SitesService.js
- express/services/index.js
- express/test/mvc/controllers/SitesController.test.js
- express/test/services/SitesService.test.js
- src/app/app.module.ts
- src/app/core/models/sites.model.ts
- src/app/core/test-mocks/sites.service.mock.ts
- src/app/shared/components/navigation/navigation.component.html
- src/app/shared/components/navigation/navigation.component.scss
- src/app/shared/components/navigation/navigation.component.spec.ts
- src/app/shared/components/navigation/navigation.component.ts
- src/app/shared/services/sites/sites.service.spec.ts
- src/app/shared/services/sites/sites.service.ts
- src/app/shared/services/user/user.service.ts
>  [BAR-626] Assign multiple site for the same user

- src/app/core/components/reporting/reporting.component.html
- src/app/core/components/reporting/reporting.component.spec.ts
- src/app/core/components/reporting/reporting.component.ts
> [BAR-653][AK] add some more validation for the report date on angular side

- src/app/core/interfaces/check-and-submit.ts
- src/app/core/models/check-and-submit.ts
- src/app/shared/components/details/details.component.html
- src/app/shared/components/details/details.component.scss
- src/app/shared/components/details/details.component.ts
- src/app/shared/components/payment-instruction-grid/payment-instruction-grid.component.html
- src/app/shared/components/payment-instruction-grid/payment-instruction-grid.component.scss
- src/app/shared/components/payment-instruction-grid/payment-instruction-grid.component.ts
https://tools.hmcts.net/jira/browse/BAR-561
Remove separator lines from check-and-submit pages where multiple fees attached to a single payment 
```
[ ] Yes
[X] No
```
> [BAR-561][AK] Remove separator lines when multiple fees attached

- package.json
- yarn.lock
https://tools.hmcts.net/jira/browse/BAR-810
Upgrade versions in the application
```
[ ] Yes
[X] No
```
> upgrade libraries versions

- acceptance-tests/test/end-to-end/pages/steps_file.js
- src/app/core/components/feelogedit/feelogedit.component.ts
- src/app/core/components/feelogedit/main/feelog.main.component.html
- src/app/core/components/payment-overview/payment-overview.component.spec.ts
- src/app/shared/components/navigation/navigation.component.html
- src/app/shared/components/navigation/navigation.component.spec.ts
- src/app/shared/components/navigation/navigation.component.ts
> BAR-710 implemented

- src/app/core/components/payment-instruction/payment-instruction.component.spec.ts
- src/app/core/components/payment-instruction/payment-instruction.component.ts
> BAR-792 implemented

- src/app/core/components/payment-instruction/payment-instruction.component.html
https://tools.hmcts.net/jira/browse/BAR-669
Add a text in payment entry confirmation page for Post clerk and Fee clerk.
```
[ ] Yes
[ x] No
```
> Code changes for BAR-669 in payment entry confirmation page

- src/app/app.module.ts
- src/app/core/components/search-results/search-results.component.html
- src/app/core/components/search-results/search-results.component.scss
- src/app/shared/components/navigation/navigation.component.html
- src/app/shared/directives/map-status-label/map-status-label.directive.spec.ts
- src/app/shared/directives/map-status-label/map-status-label.directive.ts
https://tools.hmcts.net/jira/browse/BAR-657
Create a mapping directive to rename the statuses before displaying on html page.
```
[ ] Yes
[X] No
```
> [BAR-657][AK] Mapping of status labels to a different one

- acceptance-tests/test/end-to-end/pages/steps.js
- acceptance-tests/test/end-to-end/pages/steps_file.js
- acceptance-tests/test/end-to-end/tests/BARDeliveryManager_test.js
- src/app/core/components/feelogedit/feelogedit.component.ts
- src/app/core/components/feelogedit/main/feelog.main.component.html
- src/app/core/components/payment-instruction/payment-instruction.component.html
- src/app/core/components/payment-instruction/payment-instruction.component.spec.ts
- src/app/core/components/payment-instruction/payment-instruction.component.ts
- src/app/core/components/payment-overview/payment-overview.component.spec.ts
- src/app/shared/components/navigation/navigation.component.html
- src/app/shared/components/navigation/navigation.component.spec.ts
- src/app/shared/components/navigation/navigation.component.ts
https://tools.hmcts.net/jira/browse/BAR-384
Make "Add payment information" navigation link text same as page title
```
[ ] Yes
[x ] No
```
> BAR-384 - Add payment navigation link changes

- acceptance-tests/test/end-to-end/pages/steps_file.js
- acceptance-tests/test/end-to-end/tests/BARDeliveryManager_test.js
- acceptance-tests/test/end-to-end/tests/BARMutlisite_test.js
- src/app/core/components/login-form/login-form.component.ts
- src/app/shared/services/user/user.service.ts
https://tools.hmcts.net/jira/browse/BAR-791
https://tools.hmcts.net/jira/browse/BAR-777
https://tools.hmcts.net/jira/browse/BAR-784
https://tools.hmcts.net/jira/browse/BAR-789
Creating a base functional test to cover multisite functionality
```
[ ] Yes
[X] No
```
> multisite functional tests

- acceptance-tests/test/end-to-end/pages/steps.js
- acceptance-tests/test/end-to-end/pages/steps_file.js
- acceptance-tests/test/end-to-end/tests/BARMutlisite_test.js
- acceptance-tests/test/end-to-end/tests/BARPostClerk_test.js
- src/app/core/components/payment-instruction-list/payment-instruction-list.component.html
- src/app/core/components/payment-instruction/payment-instruction.component.html
- src/app/core/components/payment-instruction/payment-instruction.component.ts
- src/app/core/components/paymentslog/paymentslog.component.html
https://tools.hmcts.net/jira/browse/BAR-641
Inconsistent title changes
```
[ ] Yes
[x ] No
```
> BAR-641 Inconsistent title changes

- src/app/core/components/reporting/reporting.component.html
https://tools.hmcts.net/jira/browse/BAR-643
Removing PDF links and updating reporting page.
```
[ ] Yes
[x ] No
```
> BAR-643 Reporting changes

- acceptance-tests/test/end-to-end/tests/BARMultisite_test.js
> BAR-785 implemented

- src/app/core/components/feelogedit/main/feelog.main.component.ts
- src/app/test-utils/feelog-main-content.ts
https://tools.hmcts.net/jira/browse/BAR-595
Field Validation – Select an Action
```
[ ] Yes
[ x] No
```
> BAR-595 Error message changes

- acceptance-tests/test/end-to-end/tests/BARMultisite_test.js
- express/services/PaymentsLogService.js
- express/test/services/PaymentsLogService.test.js
- src/app/core/components/search-results/search-results.component.html
- src/app/core/components/search-results/search-results.component.ts
- src/app/core/interfaces/payments-log.ts
- src/app/core/models/payhub-reference.model.ts
- src/app/core/models/payment-parent.model.ts
- src/app/test-utils/test-utils.ts
> BAR-803 804 implemented

- src/app/core/components/payment-overview/payment-overview.component.css
- src/app/core/components/payment-overview/payment-overview.component.html
- src/app/core/components/site-admin/site-admin.component.css
- src/app/core/components/site-admin/site-admin.component.html
- src/app/shared/components/navigation/navigation.component.html
- src/app/shared/components/navigation/navigation.component.scss
https://tools.hmcts.net/jira/browse/BAR-644
https://tools.hmcts.net/jira/browse/BAR-645
https://tools.hmcts.net/jira/browse/BAR-808
UX_Black Banner to replace Blue Black
Confirm and Cancel button separation
Renaming Delete button as Confirm
```
[ ] Yes
[x ] No
```
> BAR-web improvements added.

- src/app/core/components/feelogedit/feelogedit.component.scss
- src/app/core/components/feelogedit/feelogedit.component.ts
- src/app/core/components/feelogedit/main/feelog.main.component.html
- src/app/core/components/feelogedit/main/feelog.main.component.spec.ts
- src/app/core/components/feelogedit/main/feelog.main.component.ts
https://tools.hmcts.net/jira/browse/BAR-596
https://tools.hmcts.net/jira/browse/BAR-597
Field Validation -  "Reason for Return"
Field Validation -  "Return Comment"
```
[ ] Yes
[x ] No
```
> BAR-596 and BAR-597 changes added.

- src/app/core/components/payment-instruction/payment-instruction.component.html
- src/app/core/components/payment-instruction/payment-instruction.component.scss
https://tools.hmcts.net/jira/browse/BAR-663
Adding pound symbol for payment amount field
```
[ ] Yes
[x] No
```
> BAR-663 - Adding pound symbol for payment amount field

- src/app/core/components/feelogedit/feelogedit.component.html
- src/app/core/components/feelogedit/feelogedit.component.scss
- src/app/core/components/feelogedit/feelogedit.component.ts
- src/app/core/components/feelogedit/main/feelog.main.component.html
- src/app/core/components/feelogedit/main/feelog.main.component.spec.ts
- src/app/core/components/feelogedit/main/feelog.main.component.ts
https://tools.hmcts.net/jira/browse/BAR-599
Field Validation - "Withdraw comment"
```
[ ] Yes
[x] No
```
> BAR-599 Enable validation for withdrew option

- src/app/core/components/paymentslog/paymentslog.component.css
- src/app/core/components/paymentslog/paymentslog.component.html
https://tools.hmcts.net/jira/browse/BAR-559
Removing "Select" text and positioning "All" text
```
[ ] Yes
[x ] No
```
> BAR-559 - Removing "Select" text and positioning "All" text

- package.json
- yarn.lock
https://tools.hmcts.net/jira/browse/PAY-2129
build issue fix so update the package.json and yarn.lock
```
[ ] Yes
[ ] No
```
> PAY-2129 - Build issue fix

- acceptance-tests/test/end-to-end/tests/BARMultisite_test.js
> Test cases commented for temp fixes

- infrastructure/main.tf
Deprecation Jenkins issue changes
```
[ ] Yes
[x ] No
```
> Deprecation Jenkins issue changes

- infrastructure/prod.tfvars
https://tools.hmcts.net/jira/browse/PAY-2232
IDAM URL update for prod
```
[ ] Yes
[ x] No
```
> IDAM URL Change for prod

- src/app/core/components/feelogedit/detail/feedetail.component.html
> added change for titleCase of Jurisdiction

- charts/bar-web/values.preview.template.yaml
- src/app/shared/components/details/details.component.html
- src/app/shared/components/details/details.component.spec.ts
- src/app/shared/components/details/details.component.ts
> testing PR build

- charts/bar-web/Chart.yaml
- charts/bar-web/requirements.yaml
- charts/bar-web/values.preview.template.yaml
- src/app/core/components/payment-overview/payment-overview.component.html
> add the description in table

- acceptance-tests/test/end-to-end/pages/steps_file.js
- acceptance-tests/test/end-to-end/tests/BARAcceptanceTestConstants.js
- acceptance-tests/test/end-to-end/tests/BARMultisite_test.js
- package.json
- yarn.lock
> Modified fucntional testcases

- acceptance-tests/test/end-to-end/pages/steps_file.js
- acceptance-tests/test/end-to-end/tests/BARMultisite_test.js
> Modified fucntional test

- acceptance-tests/test/end-to-end/tests/BARDeliveryManager_test.js
- src/app/core/components/payment-overview/payment-overview.component.html
- src/app/core/components/payment-overview/payment-overview.component.ts
- src/app/core/components/site-admin/site-admin.component.html
- src/app/shared/components/navigation/navigation.component.html
BAR-633
```
[ ] Yes
[ ] No
```
> Ui changes

- .travis.yml
- Jenkinsfile_CNP
- yarn.lock
> PAY-3500 : Nightly Build issue fix

- yarn.lock
> PAY-4022 CVE fixes

- Jenkinsfile_CNP
- audit.json
> Nightly dev

- Jenkinsfile_CNP
> NIGHTLY BUILD FIX

- package.json
- yarn.lock
> properties volume upgrade

- audit.json
> Suppress security on audit file

- Jenkinsfile_nightly
- acceptance-tests/codecept.conf.js
- acceptance-tests/helper/SauceLabsReportingHelper.js
- acceptance-tests/saucelabs.conf.js
- acceptance-tests/test/end-to-end/config/BARConfig.js
- acceptance-tests/test/end-to-end/crossbrowser/supportedBrowsers.js
- acceptance-tests/test/end-to-end/tests/BARDeliveryManager_test.js
- acceptance-tests/test/end-to-end/tests/BARFeeClerk_test.js
- acceptance-tests/test/end-to-end/tests/BARMultisite_test.js
- acceptance-tests/test/end-to-end/tests/BARPostClerk_test.js
- bin/run-crossbrowser-tests.sh
- package.json
- smoke-test/test/smoke-test.js
- yarn.lock
https://tools.hmcts.net/jira/browse/PAY-5512
```
[ ] Yes
[X] No
```
> Upgrade to codeceptjs 3 add implement cross browser tests

- charts/bar-web/Chart.yaml
> Node version update in chart yaml

- Jenkinsfile_CNP
- Jenkinsfile_nightly
- acceptance-tests/codecept.conf.js
- package.json
- scripts/pa11y-urls.js
- scripts/pa11y.js
https://tools.hmcts.net/jira/browse/PAY-5670
```
[ ] Yes
[X] No
```
> pa11y tests implementation

- Jenkinsfile_nightly
> disable fortify scan

- express/mvc/controllers/PaymentInstructionController.js
> handle 403 error as it is instead of 500.

- Jenkinsfile_CNP
- Jenkinsfile_nightly
- Jenkinsfile_parameterized
- charts/bar-web/Chart.yaml
- package.json
- yarn.lock
> updated deprecated after to afterAlways

- express/mvc/controllers/PaymentInstructionController.js
- express/test/mvc/controllers/PaymentInstructionController.test.js
> add log statements

- infrastructure/main.tf
PAY-5590
Update TF.
```
[ ] Yes
[x] No
```
> PAY-5590: Update main.tf

- acceptance-tests/test/end-to-end/tests/BARDeliveryManager_test.js
https://tools.hmcts.net/jira/browse/PAY-5916
Functional test commented out section which is flakey to ensure Yarn 3 upgrade is deployed successfully.
```
[ ] Yes
[x] No
```
> PAY-5916: Fix to functional test.

- src/test/java/build.gradle
https://tools.hmcts.net/jira/browse/PAY-6443
Update to fix Fortify scan in nightly build.
```
[ ] Yes
[x] No
```
> PAY-6443: Fix for Fortify nightly build.

- acceptance-tests/test/end-to-end/pages/steps_file.js
- acceptance-tests/test/end-to-end/tests/BARDeliveryManager_test.js
- acceptance-tests/test/end-to-end/tests/BARMultisite_test.js
https://tools.hmcts.net/jira/browse/PAY-6467
```
[ ] Yes
[X] No
```
> fix nightly build failure functional tests

- audit.json
PAY_6491
Shell script fix
```
[ ] Yes
[ x ] No
```
> fix for shell script

- audit.json
PAY_6552
security issue fixed
```
[ ] Yes
[ x ] No
```
> security issue fixed

- README.md
PAY-6838
Pulling master into nightly dev
- [ x ] Does this PR introduce a breaking change
> PAY-6838v7

- README.md
PAY-6838
Pull master into nightly dev
- [ x ] Does this PR introduce a breaking change
> PAY-6838v8

- package.json
- yarn.lock
https://tools.hmcts.net/jira/browse/PAY-6974
upgrade express to address vulnerability "Open Redirect in malformed URLs"
> PAY-6974 use express 4.19.2

- package.json
- yarn.lock
[PAY-6999: Pipeline fixes - week beginning 8th April 2024
[PAY-6999] (https://tools.hmcts.net/jira/browse/PAY-6999).
> [PAY-6999: Pipeline fixes - week beginning 8th April 2024

- .github/workflows/stale.yml
- charts/bar-web/Chart.yaml
https://tools.hmcts.net/jira/browse/PAY-6981
https://tools.hmcts.net/jira/browse/PAY-6982
Node version update and stale.yml file addition 
- [ x ] Does this PR introduce a breaking change
> PAY-6982 Node version update and stale.yml file addition 

- Jenkinsfile_nightly
- acceptance-tests/helper/utils.js
- acceptance-tests/test/end-to-end/pages/steps_file.js
- acceptance-tests/test/end-to-end/tests/BARFeeClerk_test.js
- acceptance-tests/test/end-to-end/tests/BARMultisite_test.js
- acceptance-tests/test/end-to-end/tests/DuplicateTests.js
https://tools.hmcts.net/jira/browse/PAY-7100
> Fix FTs as per Fee changes

- Jenkinsfile_nightly
- package.json
- src/app/core/components/login-form/login-form.component.ts
- yarn-audit-known-issues
- yarn.lock
[PAY-7194: Pipeline fixes - week beginning 17 Jun 2024
[PAY-7194] (https://tools.hmcts.net/jira/browse/PAY-7194).
> [PAY-7194: Pipeline fixes - week beginning 17 Jun 2024

- package.json
- yarn.lock
See [PAY-7303](https://tools.hmcts.net/jira/browse/PAY-7303)
Change description
Update to version micromatch.
Testing done
Pipeline green.
> PAY-7303 cve pipeline issues addressed

- package.json
- yarn-audit-known-issues
- yarn.lock
See [PAY-7347](https://tools.hmcts.net/jira/browse/PAY-7347)
Addressing CVE vulnerbilities
Changes made on nightly dev branch and rebuilt.
> PAY-7347 cve pipeline issues addressed

- package.json
- yarn-audit-known-issues
- yarn.lock
[PAY-7470: Pipeline fixes - week beginning 18 Nov  2024
[PAY-7470] (https://tools.hmcts.net/jira/browse/PAY-7470).
> [PAY-7470: Pipeline fixes - week beginning 18 Nov  2024

- infrastructure/main.tf
https://tools.hmcts.net/jira/browse/CME-325
- [ x] commit messages are meaningful and follow good commit message guidelines
- [ x] README and other documentation has been updated / added (if needed)
- [ x] tests have been updated / new tests has been added (if needed)
> CME-325: Update azurerm

- Jenkinsfile_nightly
https://tools.hmcts.net/jira/browse/PAY-7535
App is being decommissioned.
N/A
> PAY-7535: Disable Nightly Pipeline
